sudo: required
services:
  - docker

befofe_install:
  - docker build -t rsanto27/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rsanto27/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-473271842525"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY